# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "product-of-choice"
client_id = "bbef963958739695dd75ad2fbbdf8e7b"
application_url = "https://crawford-match-degree-intervention.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://crawford-match-degree-intervention.trycloudflare.com/auth/callback",
  "https://crawford-match-degree-intervention.trycloudflare.com/auth/shopify/callback",
  "https://crawford-match-degree-intervention.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-2023-23.myshopify.com"
